reward-list:
  - "destroyer_shield"
  - "destroyer_helmet"
  - "destroyer_chestplate"
  - "destroyer_leggings"
  - "destroyer_boots"
  - "destroyer_glasses"
  - "destroyer_eardrop"
  - "destroyer_gloves"
  - "冲田总司主手"
  - "冲田总司副手"
  - "冲田总司头饰"
  - "冲田总司上装"
  - "冲田总司裤子"
  - "冲田总司鞋子"
  - "冲田总司翅膀"